export const Screens = {
  TAB_VIEW: 'tabView',
  LOGIN_SCREEN: "Login",
  NEW_PASSWORD_SCREEN: "NewPasswordScreen",
  ACCOUNT_RECOVERY_SCREEN: "AccountRecovery",
  SIGN_UP_SCREEN: "SignUp",
  CONFIRM_NUMBER_SCREEN: "ConfirmationNumberScreen",
  PROFILE: "Profile",
  CHAT_LIST: "ChatList",
  CONNECTIONS: "Connections",
  LIVE_CHAT: "LiveChat",
  TOPIC_LIST_SCREEN: "TopicListScreen",
  TOPIC_CONTENT_LIST_SCREEN:"TopicContentListScreen",
  INVITATION: "InvitationScreen",
  EDUCATIONAL_CONTENT_PIECE:"EducationalContentPiece",
  TELEHEALTH_WELCOME:"TelehealthWelcomeScreen",
  VIDEO_CALL:"VideoCallScreen",
  WAITING_ROOM:"TeleHealthWaitingRoom",
  TELEHEALTH_COMPLETED: "CompletedSessionScreen",
  MEMBER_DETAIL_SCREEN:"MemberDetailScreen",
  PENDING_CONNECTIONS_SCREEN: "PendingConnectionScreen",
  PROVIDER_SEARCH_SCREEN: "ProviderSearchScreen",
  PROGRESS_REPORT_SCREEN: "ProgressReportScreen",
  PROGRESS_REPORT_SEE_ALL_SCREEN: 'ProgressReportSeeAllScreen',
  ASSIGNABLE_CONTENT_LIST: 'AssignableContentList',
  PROVIDER_PROFILE_SCREEN: "ProviderProfileScreen",
  SHARE_CONTENT_SCREEN : "ShareContentScreen",
  OUTCOME_DETAIL_SCREEN: 'OutcomeDetailScreen',
  DCT_REPORT_VIEW_SCREEN: 'DCTReportViewScreen',
  PROGRESS_REPORT_SEE_ALL_SCREEN_DCT: 'ProgressReportSeeAllScreenDct',
  APPOINTMENTS_SCREEN: 'AppointmentsScreen',
  SETTINGS_SCREEN: 'SettingsScreen',
  SETTINGS_STACK: 'SettingsStack',
  CHANGE_PASSWORD_SCREEN: 'ChangePasswordScreen',
  APPOINTMENT_DETAILS_SCREEN: 'AppointmentDetailsScreen',
  REQUEST_APPT_SELECT_SERVICE_SCREEN: 'AppointmentSelectServiceScreen',
  REQUEST_APPT_SELECT_DATE_TIME_SCREEN: 'AppointmentSelectDateTimeScreen',
  REQUEST_APPT_SELECT_MEMBER_SCREEN: 'AppointmentSelectMemberScreen',
  MEMBER_PROHIBITIVE_SCREEN: 'PatientProhibitiveScreen',
  REQUEST_APPT_EDIT_MESSAGE_SCREEN: 'AppointmentEditMessageScreen',
  REQUEST_APPT_CONFIRM_DETAILS_SCREEN: 'AppointmentConfirmDetailsScreen',
  APPOINTMENT_SUBMITTED: 'AppointmentSubmitted',
  APPOINTMENTS_SETTINGS: 'AppointmentsSettings',
  BUSINESS_HOUR_SELECTION: 'BusinessHourSelectionScreen',
  TIME_ZONE_SELECTION: 'TimeZoneSelection',
  SERVICES_SCREEN: 'ServicesScreen',
  OPERATING_STATES: 'OperatingStates',
  ADD_SERVICE_SCREEN: 'AddServiceScreen',
  NOTIFICATION_SCREEN: 'NotificationScreen',
  SUPPORT_SCREEN: 'Support',
  ABOUT_SCREEN: 'AboutScreen',
  SECTION_LIST_SCREEN: 'SectionListScreen',
  REVIEW_DETAIL_SCREEN: 'ReviewDetailScreen',
  PRIVACY_POLICY_SCREEN: 'PrivacyPolicy',
  TERMS_OF_SERVICE_SCREEN: 'TermsOfService',
  CREATE_GROUP_SCREEN: 'CreateGroupScreen',
  ADD_MEMBERS_SCREEN: 'AddMembersScreen',
  GROUP_DETAIL_SCREEN: 'GroupDetailScreen',
  ASSIGN_ASSESSMENT: 'AssignAssessmentScreen',
  ACTIVITY_FEED_LIST_SCREEN: 'ActivityListScreen',
  SESSION_NOTES_SCREEN: 'SessionNotesScreen',
  CONVO_FEED_SCREEN: 'ConvoFeedScreen',
  CONVO_FEED_LIST_SCREEN: 'ConvoFeedListScreen',
  CONVO_DETAILS_SCREEN: 'ConvoDetailsScreen',
  EDUCATION_FEED_LIST_SCREEN: 'EducationFeedListScreen',
  APPOINTMENT_FEED_LIST_SCREEN: 'AppointmentFeedListScreen',
  USER_APPOINTMENT_LIST_SCREEN: 'UserAppointmentListScreen',
  GROUP_CALL_SCREEN: 'GroupCallScreen',
  SUGGEST_SECOND_CONNECTION_SCREEN: 'SuggestSecondConnectionScreen',
  CONNECTION_REQUEST_SCREEN: 'ConnectionRequestScreen',
  APPT_COMPLETED_NOTES_SCREEN: 'ApptCompletedNotesScreen',
  APPT_USER_LIST_SCREEN: 'AppointmentUserListScreen',
  APPT_SERVICE_SCREEN: 'AppointmentServiceScreen',
  APPT_DATE_TIME_SCREEN: 'AppointmentDateTimeScreen',
  EDIT_GROUP_RULES_SCREEN:'EditGroupRulesScreen',
  EDIT_GROUP_DONATIONS_SCREEN:'EditGroupDonationsScreen',
  APPT_CONFIRM_DETAILS_SCREEN:'RequestAppointmentConfirmDetailsScreen',
  PROVIDER_PROGRESS_SCREEN:'ProviderProgressScreen',
  GENERIC_MEDIA_VIEW: 'GenericMediaViewScreen',
  STRIPE_CONNECT_FLOW: 'StripeConnectFlow',
  SESSION_QUALITY_SCREEN: 'SessionQualityScreen',
  APPOINTMENT_RECAP_SCREEN: 'AppointmentRecapScreen',
  INTEREST_IN_OTHER: 'InterestInOtherScreen',
  SCHEDULE_NEXT_APPOINTMENT: 'ScheduleNextAppointment',
  APPOINTMENT_OVERVIEW_SCREEN: 'ApptOverviewScreen',
  PAST_APPOINTMENT_LIST_SCREEN: 'PastApptListScreen',
  REVIEW_GROUP_LIST_SCREEN: 'ReviewGroupListScreen',
  REVIEW_CHATBOT_LIST_SCREEN: 'ReviewChatbotListScreen',
  REVIEW_HISTORY_SCREEN: 'ReviewHistoryScreen',
  REVIEW_SOCIAL_DETERMINANT_SCREEN: 'ReviewSocialDeterminantScreen',
  REVIEW_LIFE_EVENT_SCREEN: 'ReviewLifeEventScreen',
  REVIEW_SYMPTOMS_SCREEN: 'ReviewSymptomScreen',
  RATE_CALL_QUALITY_SCREEN: 'RateCallQualityScreen',
  MEMBER_EMR_DETAILS_SCREEN: 'MemberEMRDetailsScreen',
  REVIEW_SINGLE_DOMAIN_TYPE: 'ReviewSingleDomainType',
  CARE_TEAM_MEMBERS_SCREEN: 'CareTeamMembersScreen',
  MEMBER_CONTACT_INFO_SCREEN: 'MemberContactInfoScreen',
  MEMBER_COMPLETED_ARTICLES: 'MemberCompletedArticles',
  ADD_PLAN_ITEMS_SCREEN: 'AddPlanItemsScreen',
  DATA_DOMAIN_LIST_SCREEN: 'DataDomainListScreen',
  DOMAIN_GROUPS_SCREEN: 'DomainGroupsScreen',
  ASSIGN_DOMAIN_ELEMENT_SCREEN: 'AssignDomainElementScreen',
  ADD_MEDICAL_HISTORY_SCREEN: 'AddMedicalHistoryScreen',
  SUBSTANCE_USE_LIST_SCREEN: 'SubstanceUseListScreen',
  REVIEW_DIAGNOSES_SCREEN: 'ReviewDiagnosesScreen',
  REVIEW_MEDICATIONS_SCREEN: 'ReviewMedicationsScreen',
  ADD_APPOINTMENT_NOTES_SCREEN: 'AddAppointmentNotesScreen',
  NEW_GROUP_DETAILS_SCREEN: 'NewGroupDetailsScreen',
  NEW_EDIT_GROUP_DETAILS_SCREEN: 'NewEditGroupDetailsScreen',
  MANAGE_GROUP_MEMBERS_SCREEN: 'ManageGroupMembersScreen',
  TELE_SESSION_V2: 'TelehealthSessionV2Screen',
  PROVIDER_DETAIL_SCREEN_V2: 'ProviderDetailScreenV2',
  PROVIDER_DAILY_SCHEDULE_SCREEN: 'ProviderDailySchedule',
  PROVIDER_ALL_SCHEDULE_SCREEN : 'ProviderAllScheduleScreen',
  NOTES_SCREEN: 'NotesScreen',
  ADD_NEW_NOTES_SCREEN: 'AddEditContactNotesScreen',
  REMOVE_NOTES_SCREEN: 'RemoveNotesScreen',
};
